FROM alpine:latest
CMD echo "+-----------------------------------------+"\
&& echo "|   UNIVERSIDAD COOPERATIVA DE COLOMBIA   |"\
&& echo "+-----------------------------------------+"\
&& echo "|   By. Sebastian Espinosa B.             |"\
&& echo "+-----------------------------------------+"