CREATE TABLE ETL.PEREZ (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT PEREZ PRIMARY KEY (id)
);

CREATE TABLE ETL.GOMEZ (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT GOMEZ PRIMARY KEY (id)
);

CREATE TABLE ETL.MARTINEZ (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT MARTINEZ PRIMARY KEY (id)
);

CREATE TABLE ETL.LOPEZ (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT LOPEZ PRIMARY KEY (id)
);

CREATE TABLE ETL.TORRES (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT TORRES PRIMARY KEY (id)
);

CREATE TABLE ETL.OTROS (
    ID NUMBER(10),
    NUMERO_IDENTIDAD NUMBER(10),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CONSTRAINT OTROS PRIMARY KEY (id)
);